In [ ]:

import numpy as np
#Create a array in python with the help of Numpy by passing elements in Tuples
arr = np.array((1,2,3,4))
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1 2 3 4]


In [ ]:
#Create an array in Python with the help of numpy by passing elements in List
brr = np.array([1,2,3,4,5,6,7],dtype='int16')
print(type(brr))
print(brr)

<class 'numpy.ndarray'>
[1 2 3 4 5 6 7]


In [ ]:
#Create an empty array...
crr = np.array(())
print(crr)
print(type(crr))

[]
<class 'numpy.ndarray'>


In [ ]:

import numpy as np
drr = np.array([6,7,8])
print(type(drr))
print(drr)

<class 'numpy.ndarray'>
[6 7 8]


In [ ]:

err = np.array([1,4.5,6.7],dtype='int16')
print(err)

[1 4 6]


In [ ]:
#Create an array wth the help of Arange Function
#In arange Function we were only pass a start and end values and within that range array of that element is created..
a = np.arange(1,5)
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:

mixedelement = np.array([1,2,3.4,5.6])
print(mixedelement)
print(type(mixedelement))
print(type(a[0]))

[1.  2.  3.4 5.6]
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [ ]:

# Arange function to create 1d array of floating Values
c = np.arange(0.0,5.2)
print(c)

NameError: ignored

In [ ]:
d = np.array([1,3,6,8.5,9.7,2.3,'Hii','Pradhumna'])
print(d)

['1' '3' '6' '8.5' '9.7' '2.3' 'Hii' 'Pradhumna']


In [ ]:
# 2D array with dimension 2x2
e = np.array([[1,2,3],[4,5,6]])
print(e)

[[1 2 3]
 [4 5 6]]


In [ ]:
f = np.array([[1,2.4,'This'],["Under",67,9.87]])
print(f)

[['1' '2.4' 'This']
 ['Under' '67' '9.87']]


In [ ]:
fe = np.array([[1,2.4,'This'],["Under",67,9.87]],dtype='str')
print(fe)

[['1' '2.4' 'This']
 ['Under' '67' '9.87']]


In [ ]:
#shape return length of correspoinding array dimension.
print(np.shape([1,2,3]))

(3,)


In [ ]:
#Eye function in numpy
print(np.eye(3))
np.zeros(3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([0., 0., 0.])

In [ ]:
#3D array
import numpy as np
d3 = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
print(d3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
print(d3[0][0])
print(d3[2][1])
print(d3[2][3])

0
9
11


In [ ]:

d3[0][0]


0

In [ ]:

d3[1]

array([4, 5, 6, 7])

In [ ]:

d3[0:12]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
print(d3[0,:,3])

IndexError: ignored

In [ ]:
d3[1:0 , 2:1]

array([], shape=(0, 0), dtype=int64)

In [ ]:
d3[4,6]

IndexError: ignored

In [ ]:

#To print a Cloumn 1 if we print any column then we use below syntax.
d3[ :,1]

array([1, 5, 9])

In [ ]:

d3[ :,3]

array([ 3,  7, 11])

In [ ]:

d3[0:0 , 1:1]

array([], shape=(0, 0), dtype=int64)

In [ ]:
a=np.array((1,2,43))
#Return a Reverse Order
a[::-1]

array([43,  2,  1])

In [ ]:
prr=np.ravel((1,2,4,5))
prr


array([1, 2, 4, 5])

In [ ]:
arr1=np.ravel(a)
arr1

array([ 1,  2, 43])

In [ ]:
a.reshape(3,1)

array([[ 1],
       [ 2],
       [43]])

In [ ]:
a.reshape(1,3)

array([[ 1,  2, 43]])

In [ ]:
# @ is used in numpy that multiply 2 arrays in row not in column..


In [ ]:
# np.multiply(arr,brr)
#multiply an element with a pericular element to element wise.


In [ ]:
#np.dot(arr,brr)

In [ ]:
arr = np.array([1,2,3])


In [ ]:
brr = np.array([[1,2,3],[4,5,6],[7,8,9]])


In [ ]:
brr@arr

array([14, 32, 50])

In [ ]:
np.multiply(arr,brr)

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [ ]:
np.dot(arr,brr)

array([30, 36, 42])

In [ ]:
np.cross(arr,arr)

array([0, 0, 0])

In [ ]:
crr = np.arange(9).reshape(3,3)
crr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
brr*crr

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72]])

In [ ]:
import numpy
arr = numpy.array([1, 5, 4, 8, 3, 7])
max_element = numpy.max(arr)
min_element = numpy.min(arr)
print('maximum element in the array is: ',
      max_element)
print('minimum element in the array is: ',
      min_element)

maximum element in the array is:  8
minimum element in the array is:  1


In [ ]:
import numpy as np
m1 = np. array([[1,4,7],[2,5,8]])
m2 = np. array([[1,4],[2,5],[3,6]])
m3 = np. dot(m1,m2)
print(m3)

[[30 66]
 [36 81]]


In [ ]:
import numpy as np

x = np.array([100,20,34])
print("Size of the array: ",
      x.size)
  
print("Memory size of one array element in bytes: ",
      x.itemsize)
print("Memory size of numpy array in bytes:",
      x.size * x.itemsize)

Size of the array:  3
Memory size of one array element in bytes:  8
Memory size of numpy array in bytes: 24


In [ ]:
arr = np.arange(24).reshape(2,3,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
arr[...,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [ ]:
arr[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#19
arr[0,1,[0,2]]

array([4, 6])

In [ ]:
#23
a = arr[0,:,3]
brr = np.flipud(a)
brr

array([11,  7,  3])

In [ ]:

arr[0,[0,2],3]

array([ 3, 11])

In [ ]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
arr.transpose()

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [ ]:

A = np.array([[0,1],[2,3],[4,5]])
#A
#A.astype(float)
A.astype("float64")
#A.astype("bool")

array([[0., 1.],
       [2., 3.],
       [4., 5.]])